Add tolerance for automatic alerts for the model regression tests

diff --git a/.github/workflows/ci-model-regression-on-schedule.yml b/.github/workflows/ci-model-regression-on-schedule.yml
--- a/.github/workflows/ci-model-regression-on-schedule.yml
+++ b/.github/workflows/ci-model-regression-on-schedule.yml
@@ -5,6 +5,7 @@ on:
   schedule:
     # Run once a week
     - cron:  '1 23 * * */7'
+  pull_request: # TODO remove later
 
 env:
   GKE_ZONE: us-central1
@@ -89,6 +90,8 @@ jobs:
       # Determine where CUDA and Nvidia libraries are located. TensorFlow looks for libraries in the given paths
       LD_LIBRARY_PATH: "/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64"
       ACCELERATOR_TYPE: "GPU"
+      GITHUB_ISSUE_TITLE: 'Scheduled Model Regression Test Failed'
+
     runs-on: [self-hosted, gpu]
     strategy:
       max-parallel: 1
@@ -222,80 +225,103 @@ jobs:
           name: report.json
           path: ./report.json
 
-      - name: Pick an assignee randomly
+      - name: Check duplicate issue
         if: failure()
-        id: pick_assignee
-        run: |
-          ASSIGNEES_LIST=("dakshvar22" "Ghostvv" "JEM-Mosig" "tttthomasssss" "samsucik" "koernerfelicia" "kedz" "aeshky")
-          # Randomly select an item from assignees list
-          ASSIGNEE=${ASSIGNEES_LIST[ $(( RANDOM % ${#ASSIGNEES_LIST[@]} )) ]}
-          echo "::set-output name=assignee::$ASSIGNEE"
-
-      - name: Open GitHub Issue 📬
-        if: failure()
-        uses: rishabhgupta/git-action-issue@v2
-        id: open_issue
+        uses: actions/github-script@v3
+        id: issue-exist
         with:
-            token: ${{ secrets.GITHUB_TOKEN }}
-            title: "Scheduled Model Regression Test Failed"
-            body: "*This PR is automatically created by the Scheduled Model Regression Test workflow. Checkout the Github Action Run [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).* <br> --- <br> **Description of Problem:** <br> Scheduled Model Regression Test failed. <br> **Configuration**: ${{ matrix.config }} <br> **Dataset**: ${{ matrix.dataset}}"
-            assignees: ${{ steps.pick_assignee.outputs.assignee }}
-
-      - name: Add Label to the Issue
-        if: failure()
-        id: add_label
-        run: |
-          # Get issue number
-          ISSUE_NUMBER=$(echo '${{ steps.open_issue.outputs.issue }}' | jq -r '.number')
-          echo "::set-output name=issue_number::$ISSUE_NUMBER"
-
-          # Add label to the issue
-          curl \
-            -X POST \
-            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-            -H "Accept: application/vnd.github.v3+json" \
-            https://api.github.com/repos/$GITHUB_REPOSITORY/issues/${ISSUE_NUMBER}/labels \
-            -d '{"labels": ${{ env.GITHUB_ISSUE_LABELS }}}'
-
-      - name: Notify Slack of Failure 😱
-        if: failure()
-        uses: 8398a7/action-slack@v3
-        with:
-          status: custom
-          fields: workflow,job,commit,repo,ref,author,took
-          custom_payload: |
-            {
-              attachments: [{
-                fallback: 'fallback',
-                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
-                title: `${process.env.AS_WORKFLOW}`,
-                text: 'Scheduled model regression test failed :no_entry:️',
-                fields: [{
-                  title: 'Configuration',
-                  value: '${{ matrix.config }}',
-                  short: false
-                },
-                {
-                  title: 'Dataset',
-                  value: '${{ matrix.dataset }}',
-                  short: false
-                },
-                {
-                  title: 'GitHub Issue',
-                  value: `https://github.com/${{ github.repository }}/issues/${{ steps.add_label.outputs.issue_number }}`,
-                  short: false
-                },
-                {
-                  title: 'GitHub Action',
-                  value: `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`,
-                  short: false
-                }],
-                actions: [{
-                }]
-              }]
+          result-encoding: string
+          github-token: ${{ github.token }}
+          script: |
+            // Get all open issues
+            const opts = await github.issues.listForRepo.endpoint.merge({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              state: 'open',
+              labels: ${{ env.GITHUB_ISSUE_LABELS }}
+            });
+            const issues = await github.paginate(opts)
+            // Check if issue exist
+            for (const issue of issues) {
+              if (issue.title.includes('${{ env.GITHUB_ISSUE_TITLE }}') ) {
+                  console.log(`Found an exist issue \#${issue.number}. Skip the following steps.`);
+                  return 'true'
+                }
             }
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CI_MODEL_REGRESSION_TEST }}
+            return 'false'
+
+      - name: Select a member from managers team randomly
+        if: failure()
+        run: |
+          # MEMBERS=$(curl \
+          #             -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+          #             -H "Accept: application/vnd.github.v3+json" \
+          #             https://api.github.com/orgs/RasaHQ/teams/research/members)
+          # # Make sure we get a list of members
+          # [[ -z "$MEMBERS" ]] && echo "Could not find any members from the team." || true
+
+          # # Shuffle the list, then select the first member as the assignee for the issue
+          # ASSIGNEE=$(echo $MEMBERS | jq -r '.[].login' | shuf | head -n1)
+          # echo ASSIGNEE="$ASSIGNEE" >> $GITHUB_ENV
+
+          echo ASSIGNEE="${{ github.actor }}" >> $GITHUB_ENV # TODO remove later
+
+      - name: Create GitHub Issue 📬
+        id: create-issue
+        if: failure()
+        uses: actions/github-script@v3
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            var issue = await github.issues.create({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              title: '${{ env.GITHUB_ISSUE_TITLE }}',
+              labels: ${{ env.GITHUB_ISSUE_LABELS }},
+              assignees: ['${{ env.ASSIGNEE }}'],
+              body: '*This PR is automatically created by the Scheduled Model Regression Test workflow. Checkout the Github Action Run [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).* <br> --- <br> **Description of Problem:** <br> Scheduled Model Regression Test failed. <br> **Configuration**: `${{ matrix.config }}` <br> **Dataset**: `${{ matrix.dataset}}`'
+            })
+            return issue.data.number
+
+      # - name: Notify Slack of Failure 😱
+      #   if: failure()
+      #   uses: 8398a7/action-slack@v3
+      #   with:
+      #     status: custom
+      #     fields: workflow,job,commit,repo,ref,author,took
+      #     custom_payload: |
+      #       {
+      #         attachments: [{
+      #           fallback: 'fallback',
+      #           color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
+      #           title: `${process.env.AS_WORKFLOW}`,
+      #           text: 'Scheduled model regression test failed :no_entry:️',
+      #           fields: [{
+      #             title: 'Configuration',
+      #             value: '${{ matrix.config }}',
+      #             short: false
+      #           },
+      #           {
+      #             title: 'Dataset',
+      #             value: '${{ matrix.dataset }}',
+      #             short: false
+      #           },
+      #           {
+      #             title: 'GitHub Issue',
+      #             value: `https://github.com/${{ github.repository }}/issues/${{ steps.create-issue.outputs.result }}`,
+      #             short: false
+      #           },
+      #           {
+      #             title: 'GitHub Action',
+      #             value: `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`,
+      #             short: false
+      #           }],
+      #           actions: [{
+      #           }]
+      #         }]
+      #       }
+      #   env:
+      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CI_MODEL_REGRESSION_TEST }}
 
   analyse_performance:
     name: Analyse Performance
@@ -304,6 +330,8 @@ jobs:
     needs:
     - deploy_runner_gpu
     - model_regression_test_gpu
+    env:
+      GITHUB_ISSUE_TITLE: 'Scheduled Model Regression Test Performance Drops'
 
     steps:
       - name: Checkout
@@ -347,12 +375,12 @@ jobs:
           OUTPUT="${OUTPUT//$'\r'/'%0D'}"
           echo "::set-output name=report_description::${OUTPUT}"
 
-          # Remove all (-0.00) from OUTPUT.
-          # We don't want to count (-0.00) as a performance drop
-          OUTPUT=${OUTPUT//(-0.00)/}
+          # TODO remove the fake data later
+          OUTPUT='"$OUTPUT | Configuration | Intent Classification Micro F1 | Entity Recognition Micro F1 | Response Selection Micro F1 | |---------------|-----------------|-----------------|-------------------| | `BERT + DIET(bow) + ResponseSelector(bow)`<br> test: `1m30s`, train: `4m16s`, total: `5m45s`|0.7942 (0.06)|0.7529 (0.00)|0.5563 (-0.00)|\n test: `2m46s`, train: `5m5s`, total: `7m51s`|0.8727 (0.00)|0.9113 (0.00)|0.8826 (-0.06)| | `Sparse + DIET(bow) + ResponseSelector(bow)`"'
 
-          # Any (negatives) found means there is a performance drops.
-          if [[ "${OUTPUT}" =~ \(-[0-9.]+\) ]]; then
+          # Match all negatives in brackets smaller than -0.05
+          # Alert performance drop if found any
+          if [[ "${OUTPUT}" =~  \(-[0-9]+.(0[6-9]|[1-9][0-9])\) ]]; then
             echo "Some test performance scores decreased."
             echo "::set-output name=is_dropped::true"
           else
@@ -360,70 +388,94 @@ jobs:
             echo "::set-output name=is_dropped::false"
           fi
 
-      - name: Pick an assignee randomly
+      - name: Check duplicate issue
         if: steps.performance.outputs.is_dropped == 'true'
-        id: pick_assignee
-        run: |
-          ASSIGNEES_LIST=("dakshvar22" "Ghostvv" "JEM-Mosig" "tttthomasssss" "samsucik" "koernerfelicia" "kedz" "aeshky")
-          # Randomly select an item from assignees list
-          ASSIGNEE=${ASSIGNEES_LIST[ $(( RANDOM % ${#ASSIGNEES_LIST[@]} )) ]}
-          echo "::set-output name=assignee::$ASSIGNEE"
-
-      - name: Open GitHub Issue 📬
-        if: steps.performance.outputs.is_dropped == 'true'
-        uses: rishabhgupta/git-action-issue@v2
-        id: open_issue
+        uses: actions/github-script@v3
+        id: issue-exist
         with:
-            token: ${{ secrets.GITHUB_TOKEN }}
-            title: "Scheduled Model Regression Test Performance Drops"
-            body: "*This PR is automatically created by the Scheduled Model Regression Test workflow. Checkout the Github Action Run [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).* <br> --- <br> **Description of Problem:** <br>  Some test performance scores **decreased**. Please look at the following table for more details. <br> ${{ steps.performance.outputs.report_description }}"
-            assignees: ${{ steps.pick_assignee.outputs.assignee }}
+          result-encoding: string
+          github-token: ${{ github.token }}
+          script: |
+            // Get all open issues based on labels
+            const opts = await github.issues.listForRepo.endpoint.merge({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              state: 'open',
+              labels: ${{ env.GITHUB_ISSUE_LABELS }}
+            });
+            const issues = await github.paginate(opts)
 
-      - name: Add Label to the Issue
-        if: steps.performance.outputs.is_dropped == 'true'
-        id: add_label
-        run: |
-          # Get issue number
-          ISSUE_NUMBER=$(echo '${{ steps.open_issue.outputs.issue }}' | jq -r '.number')
-          echo "::set-output name=issue_number::$ISSUE_NUMBER"
-
-          # Add label to the issue
-          curl \
-            -X POST \
-            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-            -H "Accept: application/vnd.github.v3+json" \
-            https://api.github.com/repos/$GITHUB_REPOSITORY/issues/${ISSUE_NUMBER}/labels \
-            -d '{"labels": ${{ env.GITHUB_ISSUE_LABELS }}}'
-
-      - name: Notify Slack when Performance Drops 💬
-        if: steps.performance.outputs.is_dropped == 'true'
-        uses: 8398a7/action-slack@v3
-        with:
-          status: custom
-          fields: workflow,job,commit,repo,ref,author,took
-          custom_payload: |
-            {
-              attachments: [{
-                fallback: 'fallback',
-                color: 'danger',
-                title: `${process.env.AS_WORKFLOW}`,
-                text: 'Scheduled model regression test performance drops :chart_with_downwards_trend:',
-                fields: [{
-                  title: 'GitHub Issue',
-                  value: `https://github.com/${{ github.repository }}/issues/${{ steps.add_label.outputs.issue_number }}`,
-                  short: false
-                },
-                {
-                  title: 'GitHub Action',
-                  value: `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`,
-                  short: false
-                }],
-                actions: [{
-                }]
-              }]
+            // Check if issue exist by comparing title
+            for (const issue of issues) {
+              if (issue.title.includes('${{ env.GITHUB_ISSUE_TITLE }}') ) {
+                  console.log(`Found an exist issue \#${issue.number}. Skip the following steps.`);
+                  return 'true'
+                }
             }
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CI_MODEL_REGRESSION_TEST }}
+            return 'false'
+
+      - name: Select a member from managers team randomly
+        if:  steps.performance.outputs.is_dropped == 'true' && steps.issue-exist.outputs.result == 'false'
+        run: |
+          # MEMBERS=$(curl \
+          #             -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+          #             -H "Accept: application/vnd.github.v3+json" \
+          #             https://api.github.com/orgs/RasaHQ/teams/research/members)
+          # # Make sure we get a list of members
+          # [[ -z "$MEMBERS" ]] && echo "Could not find any members from the team." || true
+
+          # # Shuffle the list, then select the first member as the assignee for the issue
+          # ASSIGNEE=$(echo $MEMBERS | jq -r '.[].login' | shuf | head -n1)
+          # echo ASSIGNEE="$ASSIGNEE" >> $GITHUB_ENV
+
+          echo ASSIGNEE="${{ github.actor }}" >> $GITHUB_ENV # TODO remove later
+
+      - name: Create GitHub Issue 📬
+        id: create-issue
+        if:  steps.performance.outputs.is_dropped == 'true' && steps.issue-exist.outputs.result == 'false'
+        uses: actions/github-script@v3
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            var issue = await github.issues.create({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              title: '${{ env.GITHUB_ISSUE_TITLE }}',
+              labels: ${{ env.GITHUB_ISSUE_LABELS }},
+              assignees: ['${{ env.ASSIGNEE }}'],
+              body: '"*This PR is automatically created by the Scheduled Model Regression Test workflow. Checkout the Github Action Run [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).* <br> --- <br> **Description of Problem:** <br>  Some test performance scores **decreased**. Please look at the following table for more details. <br> ${{ steps.performance.outputs.report_description }}"'
+            })
+            return issue.data.number
+
+      # - name: Notify Slack when Performance Drops 💬
+      #   if: steps.performance.outputs.is_dropped == 'true'
+      #   uses: 8398a7/action-slack@v3
+      #   with:
+      #     status: custom
+      #     fields: workflow,job,commit,repo,ref,author,took
+      #     custom_payload: |
+      #       {
+      #         attachments: [{
+      #           fallback: 'fallback',
+      #           color: 'danger',
+      #           title: `${process.env.AS_WORKFLOW}`,
+      #           text: 'Scheduled model regression test performance drops :chart_with_downwards_trend:',
+      #           fields: [{
+      #             title: 'GitHub Issue',
+      #             value: `https://github.com/${{ github.repository }}/issues/${{ steps.create-issue.outputs.result }}`,
+      #             short: false
+      #           },
+      #           {
+      #             title: 'GitHub Action',
+      #             value: `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`,
+      #             short: false
+      #           }],
+      #           actions: [{
+      #           }]
+      #         }]
+      #       }
+      #   env:
+      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CI_MODEL_REGRESSION_TEST }}
 
   remove_runner_gpu:
     name: Delete Github Runner - GPU
