cat :)

diff --git a/.github/workflows/ci-model-regression.yml b/.github/workflows/ci-model-regression.yml
--- a/.github/workflows/ci-model-regression.yml
+++ b/.github/workflows/ci-model-regression.yml
@@ -97,8 +97,9 @@ jobs:
       id: set-matrix
       run: |-
           matrix=$(gomplate -d mapping=./dataset/dataset_config_mapping.json -d github=https://api.github.com/repos/${{ github.repository }}/issues/comments/${{ steps.fc_config.outputs.comment-id }} -H 'github=Authorization:token ${{ secrets.GITHUB_TOKEN }}' -f .github/templates/model_regression_test_config_to_json.tmpl 2> /tmp/error.txt)
+
           # If file is not empty, print error and fail the step
-          [ -s /tmp/error.txt ] && echo "::error::$(echo /tmp/error.txt)" && exit 1
+          [ -s /tmp/error.txt ] && echo "::error::$(cat /tmp/error.txt)" && exit 1
 
           matrix_length=$(echo $matrix | jq '.[] | length')
           echo "::set-output name=matrix_length::$matrix_length"
