Validate that GPUs are not working
Otherwise measurements would differ

diff --git a/.github/workflows/ci-model-regression.yml b/.github/workflows/ci-model-regression.yml
--- a/.github/workflows/ci-model-regression.yml
+++ b/.github/workflows/ci-model-regression.yml
@@ -596,6 +596,17 @@ jobs:
         if: steps.set_dataset_config_vars.outputs.is_dataset_exists == 'true' && steps.set_dataset_config_vars.outputs.is_config_exists == 'true'
         run: poetry run pip install -U datadog-api-client ddtrace
 
+      - name: Validate that GPUs are not working
+        if: steps.set_dataset_config_vars.outputs.is_dataset_exists == 'true' && steps.set_dataset_config_vars.outputs.is_config_exists == 'true'
+        run: |-
+          set -x  # debug
+          poetry run python .github/scripts/validate_gpus.py
+          retVal=$?
+          if [ $retVal -eq 0 ]; then
+              echo "Error: There are GPUs, but this test should run on CPUs only"
+              exit 1
+          fi
+
       - name: Run test
         id: run_test
         if: steps.set_dataset_config_vars.outputs.is_dataset_exists == 'true' && steps.set_dataset_config_vars.outputs.is_config_exists == 'true'
