Log a warning message if a configuration file is not available

diff --git a/.github/workflows/ci-model-regression.yml b/.github/workflows/ci-model-regression.yml
--- a/.github/workflows/ci-model-regression.yml
+++ b/.github/workflows/ci-model-regression.yml
@@ -173,8 +173,13 @@ jobs:
         run: |-
           # determine DATASET and CONFIG environment variables
           source <(gomplate -d mapping=./dataset/dataset_config_mapping.json -f .github/templates/configuration_variables.tmpl)
-          test -f dataset/configs/$CONFIG
-          test -d dataset/$DATASET
+
+          # Not all configurations are available for all datasets.
+          # The job will fail and the workflow continues, if the configuration file doesn't exist
+          # for a given dataset
+
+          test -f dataset/configs/$CONFIG || (echo "::warning::The ${{ matrix.config }} configuration file doesn't exist. Skipping the job." && exit 1)
+          test -d dataset/$DATASET || (echo "::warning::The ${{ matrix.dataset }} dataset doesn't exist. Skipping the job." && exit 1)
           echo "::set-env name=DATASET::${DATASET}"
           echo "::set-env name=CONFIG::${CONFIG}"
 
