Execute tests in the dataset directory

diff --git a/.github/workflows/ci-model-regression.yml b/.github/workflows/ci-model-regression.yml
--- a/.github/workflows/ci-model-regression.yml
+++ b/.github/workflows/ci-model-regression.yml
@@ -193,6 +193,7 @@ jobs:
           path: 'dataset'
 
       - name: Set DATASET and CONFIG variables
+        id: set_dataset_config_vars
         env:
           DATASET_NAME: "${{ matrix.dataset }}"
           CONFIG_NAME: "${{ matrix.config }}"
@@ -204,34 +205,43 @@ jobs:
           # The job will fail and the workflow continues, if the configuration file doesn't exist
           # for a given dataset
 
-          test -f dataset/configs/$CONFIG || (echo "::warning::The ${{ matrix.config }} configuration file doesn't exist. Skipping the job." && exit 1)
-          test -d dataset/$DATASET || (echo "::warning::The ${{ matrix.dataset }} dataset doesn't exist. Skipping the job." && exit 1)
+          test -f dataset/configs/$CONFIG || (echo "::warning::The ${{ matrix.config }} configuration file doesn't exist. Skipping the job." \
+            echo "::set-output name=is_dataset_exists::false" && exit 0)
+          test -d dataset/$DATASET || (echo "::warning::The ${{ matrix.dataset }} dataset doesn't exist. Skipping the job." \
+            echo "::set-output name=is_config_exists::false" && exit 0)
+          echo "::set-output name=is_dataset_exists::true"
+          echo "::set-output name=is_config_exists::true"
           echo "::set-env name=DATASET::${DATASET}"
           echo "::set-env name=CONFIG::${CONFIG}"
 
       - name: Set up Python 3.8 🐍
         uses: actions/setup-python@v2
+        if: steps.set_dataset_config_vars.outputs.is_dataset_exists == 'true' && steps.set_dataset_config_vars.outputs.is_config_exists == 'true'
         with:
           python-version: 3.8
 
       - name: Read Poetry Version 🔢
+        if: steps.set_dataset_config_vars.outputs.is_dataset_exists == 'true' && steps.set_dataset_config_vars.outputs.is_config_exists == 'true'
         run: |
           echo "::set-env name=POETRY_VERSION::$(scripts/poetry-version.sh)"
         shell: bash
 
       - name: Install poetry 🦄
         uses: Gr1N/setup-poetry@v1
+        if: steps.set_dataset_config_vars.outputs.is_dataset_exists == 'true' && steps.set_dataset_config_vars.outputs.is_config_exists == 'true'
         with:
           poetry-version: ${{ env.POETRY_VERSION }}
 
       - name: Load Poetry Cached Libraries ⬇
         uses: actions/cache@v1
+        if: steps.set_dataset_config_vars.outputs.is_dataset_exists == 'true' && steps.set_dataset_config_vars.outputs.is_config_exists == 'true'
         with:
           path: ~/.cache/pypoetry/virtualenvs
           key: ${{ runner.os }}-poetry-3.8-${{ hashFiles('**/poetry.lock') }}
           restore-keys: ${{ runner.os }}-poetry-3.8
 
       - name: Install Dependencies 📦
+        if: steps.set_dataset_config_vars.outputs.is_dataset_exists == 'true' && steps.set_dataset_config_vars.outputs.is_config_exists == 'true'
         run: |
           poetry install --extras full
           make install
@@ -239,23 +249,26 @@ jobs:
           poetry run python -m spacy link --force de_core_news_md de
 
       - name: Validate that GPUs are working
+        if: steps.set_dataset_config_vars.outputs.is_dataset_exists == 'true' && steps.set_dataset_config_vars.outputs.is_config_exists == 'true'
         run: |-
           poetry run python -c 'from tensorflow.python.client import device_lib; print(device_lib.list_local_devices())' || true
 
       - name: Run test
         id: run_test
+        if: steps.set_dataset_config_vars.outputs.is_dataset_exists == 'true' && steps.set_dataset_config_vars.outputs.is_config_exists == 'true'
         env:
           TFHUB_CACHE_DIR: ~/.tfhub_cache/
           OMP_NUM_THREADS: 1
         run: |-
           poetry run rasa --version
 
+          cd dataset
           export NOW_TRAIN=$(gomplate -i '{{ (time.Now).Format time.RFC3339}}');
-          poetry run rasa train nlu --quiet -u dataset/$DATASET/train -c dataset/configs/$CONFIG --out models/$DATASET/$CONFIG
+          poetry run rasa train nlu --quiet -u $DATASET/train -c configs/$CONFIG --out models/$DATASET/$CONFIG
           echo "::set-output name=train_run_time::$(gomplate -i '{{ $t := time.Parse time.RFC3339 (getenv "NOW_TRAIN") }}{{ (time.Since $t).Round (time.Second 1) }}')"
 
           export NOW_TEST=$(gomplate -i '{{ (time.Now).Format time.RFC3339}}');
-          poetry run rasa test nlu --quiet -u dataset/$DATASET/test -m models/$DATASET/$CONFIG --out results/$DATASET/$CONFIG
+          poetry run rasa test nlu --quiet -u $DATASET/test -m $DATASET/$CONFIG --out ${{ github.workspace }}/results/$DATASET/$CONFIG
 
           echo "::set-output name=test_run_time::$(gomplate -i '{{ $t := time.Parse time.RFC3339 (getenv "NOW_TEST") }}{{ (time.Since $t).Round (time.Second 1) }}')"
           echo "::set-output name=total_run_time::$(gomplate -i '{{ $t := time.Parse time.RFC3339 (getenv "NOW_TRAIN") }}{{ (time.Since $t).Round (time.Second 1) }}')"
@@ -264,11 +277,13 @@ jobs:
       # The report file is extended with new results every next job run
       - name: Download artifact
         uses: actions/download-artifact@v2
+        if: steps.set_dataset_config_vars.outputs.is_dataset_exists == 'true' && steps.set_dataset_config_vars.outputs.is_config_exists == 'true'
         continue-on-error: true
         with:
           name: report.json
 
       - name: Generate a JSON file with a report / Publish results to Segment
+        if: steps.set_dataset_config_vars.outputs.is_dataset_exists == 'true' && steps.set_dataset_config_vars.outputs.is_config_exists == 'true'
         env:
           SUMMARY_FILE: "./report.json"
           SEGMENT_TOKEN: ${{ secrets.SEGMENT_TOKEN }}
@@ -286,6 +301,7 @@ jobs:
           cat $SUMMARY_FILE
 
       - name: Upload an artifact with the report
+        if: steps.set_dataset_config_vars.outputs.is_dataset_exists == 'true' && steps.set_dataset_config_vars.outputs.is_config_exists == 'true'
         uses: actions/upload-artifact@v2
         with:
           name: report.json
@@ -321,40 +337,55 @@ jobs:
           sudo chmod +x /usr/local/bin/gomplate
 
       - name: Set DATASET and CONFIG variables
+        id: set_dataset_config_vars
         env:
           DATASET_NAME: "${{ matrix.dataset }}"
           CONFIG_NAME: "${{ matrix.config }}"
         run: |-
           # determine DATASET and CONFIG environment variables
           source <(gomplate -d mapping=./dataset/dataset_config_mapping.json -f .github/templates/configuration_variables.tmpl)
-          test -f dataset/configs/$CONFIG
-          test -d dataset/$DATASET
+
+          # Not all configurations are available for all datasets.
+          # The job will fail and the workflow continues, if the configuration file doesn't exist
+          # for a given dataset
+
+          test -f dataset/configs/$CONFIG || (echo "::warning::The ${{ matrix.config }} configuration file doesn't exist. Skipping the job." \
+            echo "::set-output name=is_dataset_exists::false" && exit 0)
+          test -d dataset/$DATASET || (echo "::warning::The ${{ matrix.dataset }} dataset doesn't exist. Skipping the job." \
+            echo "::set-output name=is_config_exists::false" && exit 0)
+          echo "::set-output name=is_dataset_exists::true"
+          echo "::set-output name=is_config_exists::true"
           echo "::set-env name=DATASET::${DATASET}"
           echo "::set-env name=CONFIG::${CONFIG}"
 
       - name: Set up Python 3.8 🐍
         uses: actions/setup-python@v2
+        if: steps.set_dataset_config_vars.outputs.is_dataset_exists == 'true' && steps.set_dataset_config_vars.outputs.is_config_exists == 'true'
         with:
           python-version: 3.8
 
       - name: Read Poetry Version 🔢
+        if: steps.set_dataset_config_vars.outputs.is_dataset_exists == 'true' && steps.set_dataset_config_vars.outputs.is_config_exists == 'true'
         run: |
           echo "::set-env name=POETRY_VERSION::$(scripts/poetry-version.sh)"
         shell: bash
 
       - name: Install poetry 🦄
         uses: Gr1N/setup-poetry@v1
+        if: steps.set_dataset_config_vars.outputs.is_dataset_exists == 'true' && steps.set_dataset_config_vars.outputs.is_config_exists == 'true'
         with:
           poetry-version: ${{ env.POETRY_VERSION }}
 
       - name: Load Poetry Cached Libraries ⬇
         uses: actions/cache@v1
+        if: steps.set_dataset_config_vars.outputs.is_dataset_exists == 'true' && steps.set_dataset_config_vars.outputs.is_config_exists == 'true'
         with:
           path: ~/.cache/pypoetry/virtualenvs
           key: ${{ runner.os }}-poetry-3.8-${{ hashFiles('**/poetry.lock') }}
           restore-keys: ${{ runner.os }}-poetry-3.8
 
       - name: Install Dependencies 📦
+        if: steps.set_dataset_config_vars.outputs.is_dataset_exists == 'true' && steps.set_dataset_config_vars.outputs.is_config_exists == 'true'
         run: |
           poetry install --extras full
           make install
@@ -363,18 +394,20 @@ jobs:
 
       - name: Run test
         id: run_test
+        if: steps.set_dataset_config_vars.outputs.is_dataset_exists == 'true' && steps.set_dataset_config_vars.outputs.is_config_exists == 'true'
         env:
           TFHUB_CACHE_DIR: ~/.tfhub_cache/
           OMP_NUM_THREADS: 1
         run: |-
           poetry run rasa --version
 
+          cd dataset
           export NOW_TRAIN=$(gomplate -i '{{ (time.Now).Format time.RFC3339}}');
-          poetry run rasa train nlu --quiet -u dataset/$DATASET/train -c dataset/configs/$CONFIG --out models/$DATASET/$CONFIG
+          poetry run rasa train nlu --quiet -u $DATASET/train -c configs/$CONFIG --out models/$DATASET/$CONFIG
           echo "::set-output name=train_run_time::$(gomplate -i '{{ $t := time.Parse time.RFC3339 (getenv "NOW_TRAIN") }}{{ (time.Since $t).Round (time.Second 1) }}')"
 
           export NOW_TEST=$(gomplate -i '{{ (time.Now).Format time.RFC3339}}');
-          poetry run rasa test nlu --quiet -u dataset/$DATASET/test -m models/$DATASET/$CONFIG --out results/$DATASET/$CONFIG
+          poetry run rasa test nlu --quiet -u $DATASET/test -m $DATASET/$CONFIG --out ${{ github.workspace }}/results/$DATASET/$CONFIG
 
           echo "::set-output name=test_run_time::$(gomplate -i '{{ $t := time.Parse time.RFC3339 (getenv "NOW_TEST") }}{{ (time.Since $t).Round (time.Second 1) }}')"
           echo "::set-output name=total_run_time::$(gomplate -i '{{ $t := time.Parse time.RFC3339 (getenv "NOW_TRAIN") }}{{ (time.Since $t).Round (time.Second 1) }}')"
@@ -383,11 +416,13 @@ jobs:
       # The report file is extended with new results every next job run
       - name: Download artifact
         uses: actions/download-artifact@v2
+        if: steps.set_dataset_config_vars.outputs.is_dataset_exists == 'true' && steps.set_dataset_config_vars.outputs.is_config_exists == 'true'
         continue-on-error: true
         with:
           name: report.json
 
       - name: Generate a JSON file with a report / Publish results to Segment
+        if: steps.set_dataset_config_vars.outputs.is_dataset_exists == 'true' && steps.set_dataset_config_vars.outputs.is_config_exists == 'true'
         env:
           SUMMARY_FILE: "./report.json"
           SEGMENT_TOKEN: ${{ secrets.SEGMENT_TOKEN }}
@@ -406,6 +441,7 @@ jobs:
 
       - name: Upload an artifact with the report
         uses: actions/upload-artifact@v2
+        if: steps.set_dataset_config_vars.outputs.is_dataset_exists == 'true' && steps.set_dataset_config_vars.outputs.is_config_exists == 'true'
         with:
           name: report.json
           path: ./report.json
