VO- 178 - Add sonar scan and run tests on code changes (#2964)
* Fix space issue in voice test workflow

* Add sonar scan for voice tests

* Run workflow on PR

* Testing

* Add filter to run voice workflow for code changes

* Testing

* Add voice unit tests to main ci file

* Revert - Testing

* Add new file to list of diff checker

diff --git a/.github/workflows/continous-integration.yml b/.github/workflows/continous-integration.yml
--- a/.github/workflows/continous-integration.yml
+++ b/.github/workflows/continous-integration.yml
@@ -1395,6 +1395,88 @@ jobs:
           name: PII Management in CALM Bot Integration Tests
           path: pii-management-in-calm-integration-results.xml
 
+  check-voice-code-changes:
+    runs-on: ubuntu-24.04
+    outputs:
+      voice-files: ${{ steps.filter.outputs.voice-files }}
+    steps:
+      - name: Checkout git repository 🕝
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      - id: filter
+        name: Check for changes in voice related files
+        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36  # v3.0.2
+        with:
+          filters: .github/change_filters.yml
+
+  voice_unit_tests:
+    name: Run Voice Unit Tests
+    needs: [ check-voice-code-changes ]
+    if: ${{ inputs.full_ci_mode != 'false' && (needs.check-voice-code-changes.outputs.voice-files == 'true') }}
+    runs-on: ubuntu-24.04
+    timeout-minutes: 60
+    strategy:
+      fail-fast: false
+      matrix:
+        test:
+          - test-audio-manual
+        python-version: [ 3.9, "3.10", "3.11" ]
+
+    steps:
+      - name: Check out code
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+
+      - name: Prepare the job for unit tests
+        uses: ./.github/actions/test-prerequisites
+        with:
+          PYTHON_VERSION: ${{ matrix.python-version }}
+          POETRY_CACHE_VERSION: ${{ secrets.POETRY_CACHE_VERSION }}
+
+      - name: Install Dependencies (Linux) 📦
+        # Poetry intermittently fails to install dependency if it is not PEP 517 compliant
+        # This is a workaround for that issue
+        run: |
+          sudo apt-get -y install libpq-dev
+          make install-full | tee .output
+          if grep 'The lock file is not up to date' .output; then exit 1; fi
+          make prepare-tests-ubuntu
+
+      - name: Install ddtrace on Linux
+        run: poetry run pip install -U 'ddtrace==2.10.5'
+
+      - name: Install additional dependencies for voice tests
+        if: matrix.test == 'test-audio-manual'
+        run: |
+          poetry run python -m pip install azure-cognitiveservices-speech
+
+      - name: Test Code 🔍 (multi-process)
+        env:
+          JOBS: 6
+          PYTHONUTF8: 1
+          DD_ENV: ${{ matrix.test }}
+          DD_SERVICE: rasa
+          DD_ARGS: --ddtrace --ddtrace-patch-all --junitxml=unit-tests-results.xml
+          DD_API_KEY: ${{ secrets.DD_API_KEY }}
+          RASA_PRO_LICENSE: ${{ secrets.RASA_PRO_LICENSE }}
+          CARTESIA_API_KEY: ${{ secrets.CARTESIA_API_KEY }}
+          DEEPGRAM_API_KEY: ${{ secrets.DEEPGRAM_API_KEY }}
+          AZURE_SPEECH_API_KEY: ${{ secrets.AZURE_SPEECH_API_KEY }}
+          API_DOCS_FORMAT: yaml
+        run: |
+          make ${{ matrix.test }}
+        shell: bash # bash shell is a way to make code run for both Linux and Windows
+
+      - name: Prepare test results
+        if: always()
+        run: mv coverage.xml  ${{ github.workspace }}/unit-tests-results-${{ matrix.test }}-python-${{ matrix.python-version }}.xml
+
+      - name: Save Test Results
+        if: always()
+        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
+        with:
+          name: unit-tests-results-${{ matrix.test }}-python-${{ matrix.python-version }}
+          path: |
+            ${{ github.workspace }}/unit-tests-results-${{ matrix.test }}-python-${{ matrix.python-version }}.xml
+
   unit-test:
     name: Run Unit Tests
     runs-on: ubuntu-24.04-4core
