add error handling

diff --git a/.github/workflows/run-performance-checks-on-main.yml b/.github/workflows/run-performance-checks-on-main.yml
--- a/.github/workflows/run-performance-checks-on-main.yml
+++ b/.github/workflows/run-performance-checks-on-main.yml
@@ -106,4 +106,11 @@ jobs:
               "context": {
                 "python_version": "${{ env.PYTHON_VERSION }}"
               }
-          }'
+          }' > response.txt
+
+          cat response.txt
+          SUCCESS=$(cat response.txt | jq .success)
+          if [[ "$SUCCESS" == "false" ]]; then
+            echo "Error calling Segment API"
+            exit 1
+          fi
